services:
  db:
    image: postgres:16
    container_name: local_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - localnet

volumes:
  pgdata:

networks:
  localnet:
